[project]
name = "comic"
version = "0.0.1"
description = "Graphic Narrative & Data Visualization!"
readme = "readme.txt"
requires-python = ">=3.13"
dependencies = [
    "reportlab>=4.3.1",
    "svglib>=1.5.1",
]
