[project]
name = "infographic"
version = "0.1.0"
description = "https://github.com/kiron-ang/infographic"
readme = "readme.txt"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "reportlab>=4.3.1",
    "svglib>=1.5.1",
]
